import 'package:flutter/material.dart';

class WordleCategory {
  final String id;
  final Map<String, String> name;
  final Map<String, String> description;
  final IconData icon;
  final Color color;
  final Map<String, List<String>> words;

  const WordleCategory({
    required this.id,
    required this.name,
    required this.description,
    required this.icon,
    required this.color,
    required this.words,
  });
  
  String getName(String lang) => name[lang] ?? name['en']!;
  String getDescription(String lang) => description[lang] ?? description['en']!;
  List<String> getWords(String lang) => words[lang] ?? words['en']!;
}

const List<WordleCategory> categories = [
  WordleCategory(
    id: 'classic',
    name: {'en': 'Classic', 'es': 'Clásico'},
    description: {'en': 'Everyday words', 'es': 'Palabras del día a día'},
    icon: Icons.abc,
    color: Color(0xFF6B4EFF),
    words: {
      'en': [
        'APPLE', 'BEACH', 'BRAIN', 'BREAD', 'BRUSH', 'CANDY',
        'CHAIR', 'CHART', 'CHASE', 'CHESS', 'CLOUD', 'CORAL',
        'CREAM', 'DANCE', 'DEATH', 'DIARY', 'DRAFT', 'DREAM',
        'DRINK', 'EAGLE', 'EARTH', 'FEAST', 'FLAME', 'FLASH',
        'FLOAT', 'FOCUS', 'FORCE', 'FRAME', 'GHOST', 'GIANT',
        'GLOBE', 'GRACE', 'GRAIN', 'GRAND', 'GRASS', 'GRAVE',
        'GREEN', 'GREET', 'GROSS', 'GROUP', 'GROWN', 'GUARD',
        'GUESS', 'GUEST', 'HAPPY', 'HEART', 'HONEY', 'HORSE',
        'HOTEL', 'HOUSE', 'HUMAN', 'IDEAL', 'IMAGE', 'INDEX',
        'INNER', 'INPUT', 'JELLY', 'JEWEL', 'JUDGE', 'JUICE',
        'KNOCK', 'KNIFE', 'KNOWN', 'LABEL', 'LARGE', 'LASER',
        'LATER', 'LEARN', 'LEVEL', 'LIGHT', 'LIMIT', 'LINEN',
        'LIVER', 'LOCAL', 'LOGIC', 'LOVER', 'LOWER', 'LUCKY',
        'LUNCH', 'MAGIC', 'MAJOR', 'MAKER', 'MANGO', 'MAPLE',
        'MATCH', 'MAYOR', 'MEDAL', 'MEDIA', 'METAL', 'MIGHT',
        'MINOR', 'MODEL', 'MONEY', 'MONTH', 'MORAL', 'MOTOR',
        'MOUNT', 'MOUSE', 'MOUTH', 'MOVIE', 'MUSIC', 'NERVE',
        'NIGHT', 'NOISE', 'NORTH', 'NOVEL', 'NURSE', 'OCEAN',
        'OFFER', 'OLIVE', 'ONSET', 'OPERA', 'ORBIT', 'ORDER',
        'OTHER', 'OUTER', 'OWNER', 'OZONE', 'PAINT', 'PANEL',
        'PANIC', 'PAPER', 'PATCH', 'PAUSE', 'PEACH', 'PENNY',
        'PHASE', 'PHONE', 'PHOTO', 'PIANO', 'PIECE', 'PILOT',
        'PINCH', 'PITCH', 'PIZZA', 'PLACE', 'PLAIN', 'PLANE',
        'PLANT', 'PLATE', 'PLAZA', 'POINT', 'POISE', 'POLAR',
        'POWER', 'PRESS', 'PRICE', 'PRIDE', 'PRIME', 'PRINT',
        'PRIZE', 'PROOF', 'PROUD', 'PROVE', 'PUNCH', 'PUPIL',
        'QUEEN', 'QUERY', 'QUEST', 'QUICK', 'QUIET', 'QUOTA',
        'QUOTE', 'RADAR', 'RADIO', 'RAISE', 'RALLY', 'RANCH',
        'RANGE', 'RAPID', 'RATIO', 'REACH', 'READY', 'REBEL',
        'REFER', 'REIGN', 'RELAX', 'REPLY', 'RIDER', 'RIDGE',
        'RIFLE', 'RIGHT', 'RIGID', 'RISKY', 'RIVAL', 'RIVER',
        'ROBOT', 'ROCKY', 'ROMAN', 'ROUGH', 'ROUND', 'ROUTE',
        'ROYAL', 'RUGBY', 'RULER', 'RURAL', 'SADLY', 'SAINT',
        'SALAD', 'SCALE', 'SCENE', 'SCENT', 'SCOPE', 'SCORE',
        'SCOUT', 'SCRAP', 'SENSE', 'SERVE', 'SEVEN', 'SHADE',
        'SHAKE', 'SHALL', 'SHAME', 'SHAPE', 'SHARE', 'SHARK',
        'SHARP', 'SHAVE', 'SHEEP', 'SHEER', 'SHEET', 'SHELF',
        'SHELL', 'SHIFT', 'SHINE', 'SHIRT', 'SHOCK', 'SHOOT',
        'SHORE', 'SHORT', 'SHOUT', 'SIGHT', 'SIXTH', 'SIXTY',
        'SKILL', 'SKULL', 'SLEEP', 'SLICE', 'SLIDE', 'SLOPE',
        'SMALL', 'SMART', 'SMELL', 'SMILE', 'SMOKE', 'SNAKE',
        'SOLAR', 'SOLID', 'SOLVE', 'SORRY', 'SOUND', 'SOUTH',
        'SPACE', 'SPARE', 'SPARK', 'SPEAK', 'SPEED', 'SPELL',
        'SPEND', 'SPICE', 'SPINE', 'SPLIT', 'SPOKE', 'SPORT',
        'SPRAY', 'SQUAD', 'STACK', 'STAFF', 'STAGE', 'STAIN',
        'STAKE', 'STALE', 'STAMP', 'STAND', 'STARE', 'START',
        'STATE', 'STEAK', 'STEAL', 'STEAM', 'STEEL', 'STEEP',
        'STEER', 'STICK', 'STIFF', 'STILL', 'STOCK', 'STONE',
        'STOOD', 'STORE', 'STORM', 'STORY', 'STOUT', 'STOVE',
        'STRIP', 'STUCK', 'STUDY', 'STUFF', 'STYLE', 'SUGAR',
        'SUNNY', 'SUPER', 'SURGE', 'SWAMP', 'SWEAR', 'SWEAT',
        'SWEEP', 'SWEET', 'SWIFT', 'SWING', 'SWORD', 'SWEPT',
        'TABLE', 'TASTE', 'TEACH', 'TEETH', 'TEMPO', 'THANK',
        'THEFT', 'THEIR', 'THEME', 'THERE', 'THICK', 'THIEF',
        'THING', 'THINK', 'THIRD', 'THOSE', 'THREE', 'THREW',
        'THROW', 'TIGER', 'TIGHT', 'TIMER', 'TIRED', 'TITLE',
        'TODAY', 'TOKEN', 'TOOTH', 'TOPIC', 'TOTAL', 'TOUCH',
        'TOUGH', 'TOWER', 'TOXIC', 'TRACE', 'TRACK', 'TRADE',
        'TRAIL', 'TRAIN', 'TRAIT', 'TRASH', 'TREAT', 'TREND',
        'TRIAL', 'TRIBE', 'TRICK', 'TRIED', 'TROOP', 'TRUCK',
        'TRULY', 'TRUMP', 'TRUNK', 'TRUST', 'TRUTH', 'TUMOR',
        'TWICE', 'TWIST', 'ULTRA', 'UNCLE', 'UNDER', 'UNIFY',
        'UNION', 'UNITE', 'UNITY', 'UNTIL', 'UPPER', 'UPSET',
        'URBAN', 'USAGE', 'USUAL', 'UTTER', 'VALID', 'VALUE',
        'VALVE', 'VAULT', 'VERSE', 'VIDEO', 'VIGOR', 'VIRAL',
        'VIRUS', 'VISIT', 'VISTA', 'VITAL', 'VIVID', 'VOCAL',
        'VOICE', 'VOTER', 'WASTE', 'WATCH', 'WATER', 'WEARY',
        'WEAVE', 'WEDGE', 'WHEAT', 'WHEEL', 'WHERE', 'WHICH',
        'WHILE', 'WHITE', 'WHOLE', 'WHOSE', 'WIDER', 'WIDTH',
        'WITCH', 'WOMAN', 'WORLD', 'WORRY', 'WORSE', 'WORST',
        'WORTH', 'WOULD', 'WOUND', 'WRATH', 'WRITE', 'WRONG',
        'WROTE', 'YACHT', 'YIELD', 'YOUNG', 'YOURS', 'YOUTH',
        'ZEBRA', 'ZONES',
      ],
      'es': [
        'ARBOL', 'AMIGO', 'BAILE', 'BANCO', 'BANOS', 'BARCO',
        'BEBER', 'BOLSA', 'BRAZO', 'CABRA', 'CALLE', 'CAMPO',
        'CANOA', 'CARNE', 'CASA', 'CESTA', 'CICLO', 'CIUDAD',
        'CLASE', 'COMER', 'COMETA', 'CONSEJO', 'CORAL', 'CREMA',
        'CUARTO', 'CUERO', 'DANZA', 'DATOS', 'DECIR', 'DECORAR',
        'DIENTES', 'DINERO', 'DONAR', 'DORMIR', 'DOSIS', 'ECLIPSE',
        'EDITOR', 'ELEGIR', 'EMPUJAR', 'ENVOY', 'ERROR', 'ESCALER',
        'ESTAR', 'ESTOS', 'EXCESO', 'FALDA', 'FARSA', 'FIESTA',
        'FLAMAS', 'FORJA', 'FORMA', 'FRACCION', 'FRASE', 'FRECUENT',
        'FRUTA', 'FUEGO', 'GANAR', 'GATO', 'GORRA', 'GOZAR',
        'GRADO', 'GRANO', 'GRAVA', 'GRIEGO', 'GRUPO', 'HABER',
        'HABLA', 'HACER', 'HARPA', 'HOGAR', 'HUEVO', 'IDEAL',
        'IGLESIA', 'IMAGEN', 'INDIO', 'IRIS', 'JUGAR', 'JUGO',
        'JUGO', 'KARMA', 'KILO', 'KOALA', 'LAGO', 'LECHE',
        'LENTE', 'LETRA', 'LIBRO', 'LUZ', 'LIMON', 'LLAVE',
        'LLORAR', 'LOBO', 'LUCES', 'LUGAR', 'LUNES', 'LUTO',
        'MADERA', 'MAGIA', 'MANGO', 'MANOS', 'MARCA', 'MARCO',
        'MARIA', 'MAYOR', 'MEDAL', 'MEDIA', 'METRO', 'MIEDO',
        'MINAS', 'MODO', 'MOLDE', 'MONEDA', 'MORAL', 'MOTOR',
        'MUNDI', 'MURAL', 'NARIZ', 'NOCHE', 'NORTE', 'NOTAS',
        'NUEVO', 'NUMEROS', 'OBRAS', 'OCASO', 'OLEAJE', 'ONZAS',
        'OPERA', 'OPCION', 'ORDEN', 'OTROS', 'PAPEL', 'PARTE',
        'PASO', 'PATOS', 'PATIN', 'PAVO', 'PEDIR', 'PEGAR',
        'PEINE', 'PELAR', 'PERRO', 'PIANO', 'PIEDRA', 'PIEL',
        'PISTA', 'PODER', 'POLVO', 'PONER', 'POZO', 'PRADO',
        'PRENSA', 'PRIMA', 'PRIMO', 'PRISA', 'PROSA', 'PUCHE',
        'PULSO', 'PUNTO', 'QUEJO', 'QUESO', 'QUINA', 'RADIO',
        'RAMAS', 'RAYOS', 'REGAR', 'REGIO', 'RELOJ', 'REMOS',
        'RENGLON', 'REYES', 'ROBAR', 'ROBOT', 'ROCAS', 'ROMPE',
        'ROPERO', 'ROSTRO', 'RUIDO', 'RUMOR', 'SABER', 'SABOR',
        'SACAR', 'SALIR', 'SALUD', 'SALVO', 'SANDALIA', 'SANGRE',
        'SANTA', 'SASTRE', 'SEGUR', 'SELVA', 'SENAL', 'SENOR',
        'SERIE', 'SILLA', 'SITIO', 'SOBRE', 'SOLAR', 'SONAR',
        'SORTE', 'SUBIR', 'SUERTE', 'SUENO', 'SUFRIR', 'SUMAR',
        'SUPER', 'SURCO', 'TABLA', 'TENER', 'TIEMPO', 'TIENDA',
        'TIERRA', 'TIPO', 'TOCAR', 'TOQUE', 'TOTAL', 'TOXICO',
        'TRAER', 'TRAMA', 'TRATO', 'TRECE', 'TREPO', 'TRIBU',
        'TRIGO', 'TRONO', 'TROPO', 'TUERC', 'TURNO', 'UBICA',
        'UNAS', 'UNICO', 'UNION', 'USTED', 'VALOR', 'VALLE',
        'VARIO', 'VEDER', 'VENIR', 'VERBO', 'VERDE', 'VERSO',
        'VESTIR', 'VIAJE', 'VIDRIO', 'VIGOR', 'VIOLA', 'VISITA',
        'VISTA', 'VIVIR', 'VOCAL', 'VOZ', 'YATE', 'YEMA',
        'ZAFIR', 'ZAPATO', 'ZONA',
      ],
    },
  ),
  WordleCategory(
    id: 'countries',
    name: {'en': 'Countries', 'es': 'Países'},
    description: {'en': 'Guess the country', 'es': 'Adivina el país'},
    icon: Icons.public,
    color: Color(0xFF00B894),
    words: {
      'en': [
        'AFGHANISTAN', 'ALBANIA', 'ALGERIA', 'ANGOLA', 'ARGENTINA',
        'ARMENIA', 'AUSTRALIA', 'AUSTRIA', 'BAHRAIN', 'BANGLADESH',
        'BARBADOS', 'BELARUS', 'BELGIUM', 'BELIZE', 'BENIN',
        'BHUTAN', 'BOLIVIA', 'BOSNIA', 'BOTSWANA', 'BRAZIL',
        'BRUNEI', 'BULGARIA', 'BURKINA', 'BURMA', 'BURUNDI',
        'CAMBODIA', 'CAMEROON', 'CANADA', 'CHAD', 'CHILE',
        'CHINA', 'COLOMBIA', 'COMORO', 'CONGO', 'COSTARICA',
        'CROATIA', 'CUBA', 'CYPRUS', 'CZECH', 'DENMARK',
        'DJIBOUTI', 'DOMINICA', 'ECUADOR', 'EGYPT', 'ERITREA',
        'ESTONIA', 'ETHIOPIA', 'FIJI', 'FINLAND', 'FRANCE',
        'GABON', 'GAMBIA', 'GEORGIA', 'GHANA', 'GREECE',
        'GRENADA', 'GUATEMALA', 'GUINEA', 'GUYANA', 'HAITI',
        'HONDURAS', 'HUNGARY', 'ICELAND', 'INDIA', 'INDONESIA',
        'IRAN', 'IRAQ', 'IRELAND', 'ISRAEL', 'ITALY',
        'JAMAICA', 'JAPAN', 'JORDAN', 'KAZAKHSTAN', 'KENYA',
        'KUWAIT', 'KYRGYZSTAN', 'LAOS', 'LATVIA', 'LEBANON',
        'LESOTHO', 'LIBERIA', 'LIBYA', 'LIECHTENSTEIN', 'LITHUANIA',
        'LUXEMBOURG', 'MADAGASCAR', 'MALAWI', 'MALAYSIA', 'MALDIVES',
        'MALI', 'MALTA', 'MAURITANIA', 'MAURITIUS', 'MEXICO',
        'MOLDOVA', 'MONACO', 'MONGOLIA', 'MOROCCO', 'MOZAMBIQUE',
        'NAMIBIA', 'NEPAL', 'NETHERLANDS', 'NEWZEALAND', 'NICARAGUA',
        'NIGER', 'NIGERIA', 'NORTHKOREA', 'NORWAY', 'OMAN',
        'PAKISTAN', 'PANAMA', 'PARAGUAY', 'PERU', 'PHILIPPINES',
        'POLAND', 'PORTUGAL', 'QATAR', 'ROMANIA', 'RUSSIA',
        'RWANDA', 'SAUDI', 'SENEGAL', 'SERBIA', 'SEYCHELLES',
        'SIERRALEONE', 'SINGAPORE', 'SLOVAKIA', 'SLOVENIA', 'SOMALIA',
        'SOUTHKOREA', 'SPAIN', 'SRILANKA', 'SUDAN', 'SURINAME',
        'SWEDEN', 'SWITZERLAND', 'SYRIA', 'TAIWAN', 'TAJIKISTAN',
        'TANZANIA', 'THAILAND', 'TOGO', 'TONGA', 'TRINIDAD',
        'TUNISIA', 'TURKEY', 'TUVALU', 'UGANDA', 'UKRAINE',
        'URUGUAY', 'UZBEKISTAN', 'VANUATU', 'VENEZUELA', 'VIETNAM',
        'YEMEN', 'ZAMBIA', 'ZIMBABWE',
      ],
      'es': [
        'AFGANISTAN', 'ALBANIA', 'ALEMANIA', 'ANDORRA', 'ANGOLA',
        'ARGENTINA', 'ARMENIA', 'AUSTRALIA', 'AUSTRIA', 'BAHREIN',
        'BELGICA', 'BELICE', 'BOLIVIA', 'BOSNIA', 'BRASIL',
        'BRUNEI', 'BULGARIA', 'CAMERUN', 'CAMBOYA', 'CANADA',
        'CHAD', 'CHILE', 'CHINA', 'COLOMBIA', 'COSTARICA',
        'CROACIA', 'CUBA', 'DINAMARCA', 'DOMINICA', 'ECUADOR',
        'EGIPTO', 'ELSALVADOR', 'ESTONIA', 'ETIOPIA', 'FILIPINAS',
        'FINLANDIA', 'FRANCIA', 'GABON', 'GEORGIA', 'GRECIA',
        'GUATEMALA', 'GUINEA', 'GUYANA', 'HAITI', 'HONDURAS',
        'HUNGRIA', 'INDIA', 'INDONESIA', 'IRAN', 'IRAQ',
        'IRLANDA', 'ISLANDIA', 'ISRAEL', 'ITALIA', 'JAMAICA',
        'JAPON', 'JORDANIA', 'KAZAJISTAN', 'KENIA', 'KUWAIT',
        'LAOS', 'LATVIA', 'LIBANO', 'LIBIA', 'LITUANIA',
        'LUXEMBURGO', 'MADAGASCAR', 'MALASIA', 'MALDIVAS', 'MALI',
        'MALTA', 'MEXICO', 'MOLDAVIA', 'MONACO', 'MONGOLIA',
        'MARRUECOS', 'MOZAMBIQUE', 'NAMIBIA', 'NEPAL', 'NICARAGUA',
        'NIGER', 'NIGERIA', 'NORUEGA', 'OMAN', 'PAKISTAN',
        'PANAMA', 'PARAGUAY', 'PERU', 'POLONIA', 'PORTUGAL',
        'QATAR', 'RUMANIA', 'RUSIA', 'RUANDA', 'ARABIA',
        'SENEGAL', 'SERBIA', 'SINGAPUR', 'ESLOVAQUIA', 'ESLOVENIA',
        'SOMALIA', 'ESPANA', 'SRI_LANKA', 'SUDAN', 'SUECIA',
        'SUIZA', 'SIRIA', 'TAIWAN', 'TAYIKISTAN', 'TANZANIA',
        'TAILANDIA', 'TOGO', 'TONGA', 'TRINIDAD', 'TUNEZ',
        'TURQUIA', 'UGANDA', 'UCRANIA', 'URUGUAY', 'UZBEKISTAN',
        'VENEZUELA', 'VIETNAM', 'YEMEN', 'ZAMBIA', 'ZIMBABUE',
      ],
    },
  ),
  WordleCategory(
    id: 'games',
    name: {'en': 'Video Games', 'es': 'Videojuegos'},
    description: {'en': 'Game titles', 'es': 'Títulos de videojuegos'},
    icon: Icons.sports_esports,
    color: Color(0xFFE17055),
    words: {
      'en': [
        'AMONG', 'ANGEL', 'BALDURS', 'BANJO', 'BAYONETTA',
        'BIOSHOCK', 'BLOOD', 'BREED', 'CABLE', 'CADENCE',
        'CALL_OF', 'CAMEL', 'CAPTAIN', 'CARRIER', 'CASTLEVANIA',
        'CHAMP', 'CHESS', 'CIVIL', 'COMBAT', 'COMPANION',
        'CONTRA', 'CRASH', 'CREED', 'CYBER', 'DANCE',
        'DEATH', 'DEUS_EX', 'DEVIL', 'DIALG', 'DISCO',
        'DOOM', 'DRAGON', 'DREAM', 'DRONE', 'DUNGEON',
        'DYING', 'ELDER', 'EMPIRE', 'FEAR', 'FINAL',
        'FLAME', 'FLESH', 'FLIGHT', 'FORZA', 'FROST',
        'GHOST', 'GIANT', 'GLASS', 'GODOFWAR', 'GOTHIC',
        'GRAND', 'GRAVITY', 'HADOW', 'HARRY', 'HEART',
        'HELLO', 'HORSE', 'HUMAN', 'HYLIA', 'IMPERIA',
        'JACK', 'JETSTREAM', 'JOKER', 'JUMANJI', 'JURASSIC',
        'KIRBY', 'KNIGHT', 'LAST', 'LEAGUE', 'LEGEND',
        'LEGO', 'LEONA', 'LIGHT', 'LIMIT', 'LOST',
        'LOVECRAFT', 'LUIGI', 'MAGIC', 'MAFIA', 'MAJOR',
        'MANHUNT', 'MARBLE', 'MARIO', 'MAXIMO', 'METROID',
        'MIGHT', 'MINER', 'MINION', 'MONSTER', 'MORTAL',
        'MOTOR', 'MOUNT', 'MUDDY', 'NARUTO', 'NINJA',
        'NOIRE', 'NORTH', 'OBSCURE', 'OUTLAST', 'PANDA',
        'PAPER', 'PARASITE', 'PARTY', 'PAYDAY', 'PEACH',
        'PHANTOM', 'PIKMIN', 'PILOT', 'PINBALL', 'PIXEL',
        'PLAGUE', 'PLANT', 'PLAYER', 'POKEMON', 'PRIMO',
        'PRINCE', 'QUAKE', 'RATCHET', 'RAVEN', 'RAYMAN',
        'RECORE', 'REDEAD', 'RESIDENT', 'RISING', 'ROGUE',
        'ROLL', 'ROMANCE', 'RUNES', 'RUSH', 'RYSE',
        'SAINT', 'SAMURAI', 'SCEPTER', 'SECRET', 'SENTINEL',
        'SHADOW', 'SHANTY', 'SHIFT', 'SHOOT', 'SIEGE',
        'SIM', 'SINGULAR', 'SKATE', 'SLY', 'SMASH',
        'SNAKE', 'SNIPER', 'SOULS', 'SPACE', 'SPAWN',
        'SPLIT', 'SPORE', 'SPYRO', 'STAR', 'STATE',
        'STEEL', 'STICK', 'STILL', 'STORM', 'STREETS',
        'STRIFE', 'STRIKE', 'SUPER', 'SWITCH', 'SYNDICATE',
        'TABLE', 'TEMPEST', 'TENNIS', 'TERRA', 'TETRIS',
        'THIEF', 'THORN', 'TITAN', 'TOMB', 'TOP',
        'TORNADO', 'TOXIC', 'TRACK', 'TRAIL', 'TRANSFORM',
        'TRICK', 'TRINE', 'TRON', 'TURBO', 'TYRANNY',
        'UNCHARTED', 'UNDYING', 'UNITE', 'UNITY', 'UP',
        'URBAN', 'VALKYRIE', 'VAMPIRE', 'VELOCITY', 'VIKINGS',
        'VIRTUA', 'VITA', 'VIVID', 'WACKY', 'WARIO',
        'WATCH', 'WAVE', 'WIELD', 'WILD', 'WITCH',
        'WOLF', 'WORLD', 'WORMS', 'WRECK', 'XCOM',
        'YAKUZA', 'YOSHI', 'ZELDA', 'ZOMBIE',
      ],
      'es': [
        'AMONG', 'ANGEL', 'BALDURS', 'BANJO', 'BAYONETTA',
        'BIOSHOCK', 'BLOOD', 'BREED', 'CABLE', 'CADENCE',
        'CALL_OF', 'CAMEL', 'CAPTAIN', 'CARRIER', 'CASTLEVANIA',
        'CHAMP', 'CHESS', 'CIVIL', 'COMBAT', 'COMPANION',
        'CONTRA', 'CRASH', 'CREED', 'CYBER', 'DANCE',
        'DEATH', 'DEUS_EX', 'DEVIL', 'DIALG', 'DISCO',
        'DOOM', 'DRAGON', 'DREAM', 'DRONE', 'DUNGEON',
        'DYING', 'ELDER', 'EMPIRE', 'FEAR', 'FINAL',
        'FLAME', 'FLESH', 'FLIGHT', 'FORZA', 'FROST',
        'GHOST', 'GIANT', 'GLASS', 'GODOFWAR', 'GOTHIC',
        'GRAND', 'GRAVITY', 'HADOW', 'HARRY', 'HEART',
        'HELLO', 'HORSE', 'HUMAN', 'HYLIA', 'IMPERIA',
        'JACK', 'JETSTREAM', 'JOKER', 'JUMANJI', 'JURASSIC',
        'KIRBY', 'KNIGHT', 'LAST', 'LEAGUE', 'LEGEND',
        'LEGO', 'LEONA', 'LIGHT', 'LIMIT', 'LOST',
        'LOVECRAFT', 'LUIGI', 'MAGIC', 'MAFIA', 'MAJOR',
        'MANHUNT', 'MARBLE', 'MARIO', 'MAXIMO', 'METROID',
        'MIGHT', 'MINER', 'MINION', 'MONSTER', 'MORTAL',
        'MOTOR', 'MOUNT', 'MUDDY', 'NARUTO', 'NINJA',
        'NOIRE', 'NORTH', 'OBSCURE', 'OUTLAST', 'PANDA',
        'PAPER', 'PARASITE', 'PARTY', 'PAYDAY', 'PEACH',
        'PHANTOM', 'PIKMIN', 'PILOT', 'PINBALL', 'PIXEL',
        'PLAGUE', 'PLANT', 'PLAYER', 'POKEMON', 'PRIMO',
        'PRINCE', 'QUAKE', 'RATCHET', 'RAVEN', 'RAYMAN',
        'RECORE', 'REDEAD', 'RESIDENT', 'RISING', 'ROGUE',
        'ROLL', 'ROMANCE', 'RUNES', 'RUSH', 'RYSE',
        'SAINT', 'SAMURAI', 'SCEPTER', 'SECRET', 'SENTINEL',
        'SHADOW', 'SHANTY', 'SHIFT', 'SHOOT', 'SIEGE',
        'SIM', 'SINGULAR', 'SKATE', 'SLY', 'SMASH',
        'SNAKE', 'SNIPER', 'SOULS', 'SPACE', 'SPAWN',
        'SPLIT', 'SPORE', 'SPYRO', 'STAR', 'STATE',
        'STEEL', 'STICK', 'STILL', 'STORM', 'STREETS',
        'STRIFE', 'STRIKE', 'SUPER', 'SWITCH', 'SYNDICATE',
        'TABLE', 'TEMPEST', 'TENNIS', 'TERRA', 'TETRIS',
        'THIEF', 'THORN', 'TITAN', 'TOMB', 'TOP',
        'TORNADO', 'TOXIC', 'TRACK', 'TRAIL', 'TRANSFORM',
        'TRICK', 'TRINE', 'TRON', 'TURBO', 'TYRANNY',
        'UNCHARTED', 'UNDYING', 'UNITE', 'UNITY', 'UP',
        'URBAN', 'VALKYRIE', 'VAMPIRE', 'VELOCITY', 'VIKINGS',
        'VIRTUA', 'VITA', 'VIVID', 'WACKY', 'WARIO',
        'WATCH', 'WAVE', 'WIELD', 'WILD', 'WITCH',
        'WOLF', 'WORLD', 'WORMS', 'WRECK', 'XCOM',
        'YAKUZA', 'YOSHI', 'ZELDA', 'ZOMBIE',
      ],
    },
  ),
  WordleCategory(
    id: 'animals',
    name: {'en': 'Animals', 'es': 'Animales'},
    description: {'en': 'World fauna', 'es': 'Fauna del mundo'},
    icon: Icons.pets,
    color: Color(0xFF0984E3),
    words: {
      'en': [
        'BADGE', 'BALDY', 'BARB', 'BASS', 'BEAGLE',
        'BEAR', 'BEETLE', 'BILL', 'BISON', 'BITTERN',
        'BOBCAT', 'BONITO', 'BULL', 'BUNNY', 'BURRO',
        'BUZZARD', 'CAMEL', 'CAPYBARA', 'CARIBOU', 'CAT',
        'CHEETAH', 'CHICK', 'CHICKEN', 'CHINCHILLA', 'CHIPMUNK',
        'CIVET', 'COBRA', 'COCK', 'COLT', 'CONDOR',
        'COOT', 'COW', 'COYOTE', 'CRAB', 'CRANE',
        'CROC', 'CROW', 'CUCKOO', 'DEER', 'DESMAN',
        'DINGO', 'DOG', 'DONKEY', 'DORMOUSE', 'DRAKE',
        'DRONGO', 'DUCK', 'DUGONG', 'EAGLE', 'ECHIDNA',
        'EGRET', 'ELAND', 'ELK', 'EMU', 'ERMIN',
        'FALCON', 'FERRET', 'FINCH', 'FISH', 'FLAMINGO',
        'FLY', 'FOAL', 'FOX', 'FROG', 'GAUR',
        'GAZELLE', 'GECKO', 'GNAT', 'GOAT', 'GORAL',
        'GORILLA', 'GOSHAWK', 'GRACKLE', 'GRIZZLY', 'GROUSE',
        'GUANACO', 'GUINEA', 'HAMSTER', 'HARE', 'HAWK',
        'HAZEL', 'HEDGEHOG', 'HEN', 'HERON', 'HIND',
        'HOATZIN', 'HORNBILL', 'HORSE', 'HOUND', 'HUMAN',
        'HYENA', 'IBEX', 'IBIS', 'IMPALA', 'JACKAL',
        'JAGUAR', 'JERBOA', 'KAKAPO', 'KANGAROO', 'KING',
        'KIT', 'KOALA', 'KOMODO', 'KUDU', 'LAMB',
        'LAPWING', 'LARK', 'LECHWE', 'LEMUR', 'LEOPARD',
        'LION', 'LLAMA', 'LOBSTER', 'LOCUST', 'LOON',
        'LORIS', 'LIZARD', 'MACAW', 'MAGPIE', 'MALAMUT',
        'MANDRILL', 'MANGABEY', 'MANTA', 'MARE', 'MARMOS',
        'MARMOT', 'MEERKAT', 'MINK', 'MOLE', 'MONKEY',
        'MOOSE', 'MOTH', 'MOUSE', 'MUSK', 'MUSKRAT',
        'NARWHAL', 'NENE', 'NIGHTINGALE', 'NUTRIA', 'OCELOT',
        'OCTOPUS', 'OLM', 'OPAH', 'OPPOSSUM', 'ORANGUTAN',
        'ORCA', 'OSTRICH', 'OTTER', 'OWL', 'OX',
        'PANDA', 'PANTHER', 'PARROT', 'PARTRIDGE', 'PEACOCK',
        'PECCARY', 'PELICAN', 'PERCH', 'PIG', 'PIGEON',
        'PIKA', 'PIRANHA', 'POLAR', 'PONY', 'PORCUPINE',
        'POSSUM', 'PRAIRIE', 'PTARMIGAN', 'PUFFIN', 'PUMA',
        'QUAIL', 'QUELEA', 'QUETZAL', 'RABBIT', 'RACCOON',
        'RAT', 'RAVEN', 'REINDEER', 'RHEA', 'RHINOCEROS',
        'ROADRUNNER', 'ROBIN', 'RODENT', 'ROOSTER', 'SABLE',
        'SALMON', 'SAND', 'SANDPIPER', 'SARDINE', 'SCARLET',
        'SCORPION', 'SEA', 'SEAL', 'SERPENT', 'SHARK',
        'SHEEP', 'SHELDRAKE', 'SHREW', 'SHRIKE', 'SHRIMP',
        'SLOTH', 'SNAIL', 'SNAKE', 'SNAPPER', 'SNOOK',
        'SNOWLEOPARD', 'SPARROW', 'SPIDER', 'SPHYNX', 'SQUID',
        'SQUIRREL', 'STAG', 'STARFISH', 'STORK', 'STOAT',
        'STURGEON', 'SWAN', 'SWORDFISH', 'TAPIR', 'TARSIER',
        'TERMITE', 'TERN', 'TIGER', 'TOAD', 'TORTOISE',
        'TOUCAN', 'TROGON', 'TROUT', 'TURTLE', 'URIAL',
        'VICUNA', 'VULTURE', 'WALRUS', 'WARTHOG', 'WASP',
        'WHALE', 'WOLF', 'WOMBAT', 'WOODCHUCK', 'WOODPECKER',
        'WREN', 'YAK', 'ZEBRA',
      ],
      'es': [
        'AGUILA', 'ALCE', 'ANTELOPE', 'ARDILLA', 'ASNO',
        'BAQUER', 'BISONT', 'BUEY', 'BULLDOG', 'BUFALO',
        'CABRA', 'CABALLO', 'CAMELLO', 'CANARIO', 'CANGURO',
        'CARACOL', 'CARIBOU', 'CASTOR', 'CEBRA', 'CERDO',
        'CHIEN', 'CHIVO', 'CONEJO', 'CONDOR', 'COBRA',
        'COYOTE', 'CROCODILO', 'CUKL', 'CUERVO', 'DELFIN',
        'DINGO', 'FALCON', 'FENIX', 'FOCA', 'GATO',
        'GAVIOTA', 'GECKO', 'GOLONDRINA', 'GORILA', 'GORRI',
        'HALCON', 'HAMSTER', 'HIENA', 'HORMIGA', 'IGUANA',
        'JAGUAR', 'JIRAFA', 'JUMENTO', 'JABALI', 'KOALA',
        'LAGARTO', 'LAGOSTA', 'LEON', 'LEOPARDO', 'LOBO',
        'LOMBRIZ', 'LORO', 'MANATI', 'MANDRIL', 'MAPACHE',
        'MARMOTA', 'MOFLE', 'MONO', 'MOSCA', 'MURCIELAGO',
        'NUTRIA', 'OCELOTE', 'OVEJA', 'PANTERA', 'PAON',
        'PATO', 'PAVO', 'PERDIZ', 'PERRO', 'PEZ',
        'PINGUINO', 'PUMA', 'RANA', 'RATA', 'RATON',
        'RENO', 'RINOCEROTE', 'SALMON', 'SALTAMONTES', 'SERPIENTE',
        'SURICATA', 'TIGRE', 'TORTUGA', 'TORO', 'TUCAN',
        'VACA', 'VIBORA', 'ZORRO',
      ],
    },
  ),
  WordleCategory(
    id: 'sports',
    name: {'en': 'Sports', 'es': 'Deportes'},
    description: {'en': 'Sports terminology', 'es': 'Terminología deportiva'},
    icon: Icons.sports_soccer,
    color: Color(0xFFFDCB6E),
    words: {
      'en': [
        'BASKETBALL', 'BATON', 'BIRDIE', 'BLITZ', 'BOWLING',
        'BOXING', 'BRONZE', 'BUCKET', 'CADDIE', 'CARRY',
        'CHECK', 'CHEST', 'CHUNK', 'CLUB', 'COACH',
        'CORNER', 'CRAMP', 'CRICKET', 'CROSS', 'CURVE',
        'DARTS', 'DEUCE', 'DIVOT', 'DODGE', 'DOUBLE',
        'DRAFT', 'DRIBBLE', 'DRIVE', 'EAGLE', 'EDGE',
        'FAIRWAY', 'FENCE', 'FIELD', 'FIFTY', 'FINISH',
        'FLIGHT', 'FLUKE', 'FORCE', 'FOUL', 'FREE',
        'FROST', 'FUMBLE', 'FURY', 'GAUGE', 'GLIDE',
        'GLOVE', 'GOLF', 'GRAND', 'GRIP', 'GROSS',
        'HAIL', 'HALFTIME', 'HAMMER', 'HANDLE', 'HARD',
        'HARNESS', 'HASTE', 'HEAD', 'HEART', 'HEATS',
        'HOCKEY', 'HOIST', 'HOLES', 'HONOR', 'HOOK',
        'HOOPS', 'HORSE', 'HURDLE', 'HURRY', 'INNING',
        'JAB', 'JOCKEY', 'JUDGE', 'JUICE', 'JUICY',
        'JUMBO', 'KAYAK', 'KICK', 'KNEEL', 'KNIFE',
        'KNIT', 'KNOCK', 'KNOLL', 'LANCE', 'LAP',
        'LAYER', 'LEAD', 'LEAF', 'LEAP', 'LEGS',
        'LIFT', 'LIMIT', 'LINEUP', 'LUNGE', 'LYNX',
        'MAGIC', 'MANIA', 'MARATHON', 'MARCH', 'MARSH',
        'MASK', 'MATCH', 'MAUL', 'MEDAL', 'MELON',
        'METRO', 'MIGHT', 'MINUS', 'MODEL', 'MONEY',
        'MONTH', 'MOTOR', 'MOTTO', 'MOUND', 'MOUNT',
        'MOUTH', 'MUDDY', 'NET', 'NICK', 'NIGHT',
        'NINTH', 'NORTH', 'NOVEL', 'OLYMPIC', 'OPENS',
        'OVERT', 'OXTER', 'PAINT', 'PANIC', 'PANEL',
        'PAR', 'PARITY', 'PASS', 'PENAL', 'PITCH',
        'PIXEL', 'PLACE', 'PLAN', 'PLANT', 'PLAY',
        'PLAYER', 'POINT', 'POLO', 'POWER', 'PRIME',
        'PRINT', 'PRIZE', 'PROOF', 'PUCK', 'PUNCH',
        'PURSUIT', 'QUARTER', 'QUARTZ', 'QUEUE', 'QUICK',
        'QUIET', 'QUOTA', 'RACE', 'RACER', 'RAISE',
        'RALLY', 'RAM', 'RANCH', 'RANGE', 'RAPID',
        'RATIO', 'REACH', 'READY', 'REBEL', 'REFER',
        'REIGN', 'RELAY', 'RENEW', 'RIDER', 'RIFLE',
        'RINK', 'RISKY', 'RIVAL', 'ROAD', 'ROBOT',
        'ROUND', 'ROW', 'RUGBY', 'RUN', 'RUNNER',
        'RUSH', 'SAIL', 'SAVE', 'SCORE', 'SCOUT',
        'SCULL', 'SERVE', 'SHANK', 'SHOOT', 'SHOT',
        'SHOVE', 'SHUTTLE', 'SIDE', 'SINGLE', 'SKATE',
        'SKIP', 'SLAM', 'SLAP', 'SLATE', 'SLIDE',
        'SLIT', 'SLOPE', 'SMASH', 'SNAG', 'SNAP',
        'SNIPE', 'SOAR', 'SOCCER', 'SOLID', 'SOLVE',
        'SPAR', 'SPEED', 'SPELL', 'SPENT', 'SPIN',
        'SPIKE', 'SPIT', 'SPOT', 'SPRINT', 'SQUAD',
        'STACK', 'STAGE', 'STAIN', 'STAKE', 'STAMP',
        'STAND', 'STARE', 'START', 'STATE', 'STEAL',
        'STEAM', 'STEEL', 'STEEP', 'STICK', 'STIFF',
        'STILL', 'STOCK', 'STONE', 'STOOD', 'STORE',
        'STORM', 'STORY', 'STOUT', 'STOVE', 'STRIKE',
        'STRING', 'STRIP', 'STUCK', 'STUDY', 'STUFF',
        'STUMP', 'STYLE', 'SUGAR', 'SUITE', 'SUPER',
        'SURGE', 'SURVEY', 'SWIM', 'TACKLE', 'TEAM',
        'TEMPO', 'TENNIS', 'TENTH', 'THIRD', 'THROW',
        'TIGHT', 'TIMER', 'TITLE', 'TOUCH', 'TOURN',
        'TOWER', 'TRACK', 'TRADE', 'TRAIL', 'TRAIN',
        'TRAIT', 'TRAMP', 'TRAWL', 'TREAT', 'TREND',
        'TRIAL', 'TRIBE', 'TRICK', 'TRIED', 'TRIPLE',
        'TROPHY', 'TRUCK', 'TRULY', 'TRUMP', 'TRUNK',
        'TURF', 'TWIST', 'ULTRA', 'UMP', 'UNDER',
        'UNION', 'UNITE', 'UNITY', 'UPPER', 'UPSET',
        'URBAN', 'USAGE', 'USUAL', 'VALID', 'VALUE',
        'VAULT', 'VERSE', 'VIGOR', 'VINYL', 'VIRUS',
        'VISIT', 'VISTA', 'VITAL', 'VIVID', 'VOCAL',
        'VOICE', 'VOTER', 'WAIST', 'WASTE', 'WATCH',
        'WATER', 'WAVE', 'WEAR', 'WEDGE', 'WEIRD',
        'WHEEL', 'WHERE', 'WHICH', 'WHILE', 'WHITE',
        'WHOLE', 'WIDTH', 'WIN', 'WIND', 'WINGS',
        'WINK', 'WINS', 'WIRY', 'WISE', 'WISH',
        'WITHIN', 'WIZARD', 'WOKE', 'WOLF', 'WOMEN',
        'WOOD', 'WORK', 'WORLD', 'WORRY', 'WORSE',
        'WORST', 'WORTH', 'WOULD', 'WOUND', 'WRAP',
        'WRIST', 'WRITE', 'WRONG', 'WRESTLE', 'YACHT',
        'YARD', 'YARN', 'YEAR', 'YELL', 'YIELD',
        'YOKE', 'YOUNG', 'YOURS', 'YOUTH', 'ZONE',
      ],
      'es': [
        'BASQUE', 'BATEO', 'BIRDIE', 'BLITZ', 'BOLICHE',
        'BOXEO', 'BRONCE', 'BUCKET', 'CADDIE', 'CARRERA',
        'CHECK', 'PECHO', 'CHUNK', 'EQUIPO', 'ENTRENADOR',
        'CORNER', 'CRAMP', 'CRICKET', 'CRUZ', 'CURVA',
        'DARTE', 'DEUCE', 'DIVOT', 'DODGE', 'DOBLE',
        'DRAFT', 'DRIBBLE', 'DRIVE', 'AGUILA', 'BORDE',
        'FAIRWAY', 'CERCA', 'CAMPO', 'FIFTY', 'FINISH',
        'VUELO', 'FLUKE', 'FUERZA', 'FOUL', 'LIBRE',
        'FROST', 'FUMBLE', 'FURIA', 'GAUGE', 'DESLIZ',
        'GUANTE', 'GOLF', 'GRANDE', 'AGARRE', 'GROSS',
        'GRANIZO', 'MEDIO', 'HAMMER', 'MANGO', 'DUREZA',
        'ARNESES', 'PRISA', 'CABEZA', 'CORAZON', 'CALIENTE',
        'HOCKEY', 'IZQUIERDA', 'HOLES', 'HONOR', 'GANCHO',
        'ANILLOS', 'CABALLO', 'OBSTACULO', 'ENTRADA', 'GOLPE',
        'JINETE', 'JUEZ', 'JUGO', 'JUGOSO', 'KAYAK',
        'PATADA', 'ARROLLADOR', 'CUCHILLO', 'NIT', 'COLINA',
        'LANZA', 'VUELTA', 'CAPA', 'LIDER', 'HOJA',
        'SALTO', 'PIERNAS', 'LIFT', 'LIMITE', 'ALINEACION',
        'LUNGE', 'LINX', 'MAGICO', 'MANIA', 'MARATON',
        'MARCHA', 'MARSH', 'MASCARA', 'PARTIDO', 'MAUL',
        'MEDALLA', 'MELON', 'METRO', 'PODER', 'MENOS',
        'MODELO', 'DINERO', 'MES', 'MOTOR', 'MOTTO',
        'MONTE', 'MOUNT', 'BOCA', 'SUDAN', 'RED',
        'NICK', 'NOCHE', 'NOVENO', 'NORTE', 'NOVELA',
        'OLIMPICO', 'ABRIR', 'EXTRA', 'OXTER', 'PINTAR',
        'PANICO', 'PANEL', 'PAR', 'PARIDAD', 'PASE',
        'PENAL', 'PITCH', 'PIXEL', 'LUGAR', 'PLAN',
        'PLANTA', 'JUGAR', 'JUGADOR', 'PUNTO', 'POLO',
        'PRIMO', 'IMPRIMIR', 'PREMIO', 'PRUEBA', 'PUCK',
        'GOLPE', 'PERSECUCION', 'CUARTO', 'CUARZO', 'COLA',
        'RAPIDO', 'QUIETO', 'CUOTA', 'CARRERA', 'CORREDOR',
        'SUBIR', 'RALLY', 'RAM', 'RANCHO', 'RANGO',
        'RATIO', 'ALCANZAR', 'LISTO', 'REBELDE', 'REFERIR',
        'REINO', 'RELEVO', 'RENOVAR', 'JINETE', 'RIFLE',
        'RINK', 'RIESGOSO', 'RIVAL', 'CAMINO', 'ROBOT',
        'RONDA', 'FILA', 'RUGBY', 'CORRER', 'CORREDOR',
        'RUSH', 'VELERO', 'SALVAR', 'MARCADOR', 'SCOUT',
        'REMO', 'SERVE', 'SHANK', 'DISPARAR', 'TIRO',
        'EMPUJE', 'SHUTTLE', 'LADO', 'SINGLE', 'PATINAR',
        'SALTAR', 'SLAM', 'NAHAP', 'LOSA', 'DESLIZ',
        'SLIT', 'PENDIENTE', 'TRAMPA', 'CHASQUIDO', 'SNIPE',
        'VOLAR', 'FUTBOL', 'SOLIDO', 'RESOLVER', 'SPAR',
        'VELOCIDAD', 'HECHIZO', 'GASTADO', 'SPIN', 'SPIKE',
        'ESPU', 'SPOT', 'SPRINT', 'ESCUDRION', 'STACK',
        'ESCENARIO', 'MANCHA', 'APUESTA', 'ESTAMPA', 'PARARSE',
        'MIRAR', 'INICIO', 'ESTADO', 'ROBAR', 'VAPOR',
        'ACERO', 'EMPINADO', 'STICK', 'RIGIDO', 'TODAVIA',
        'STOCK', 'PIEDRA', 'PARADO', 'TIENDA', 'TORMENTA',
        'HISTORIA', 'REPLENO', 'HORNO', 'STRIKE', 'CUERDA',
        'STRIP', 'ATASCADO', 'ESTUDIO', 'COSAS', 'STUMP',
        'ESTILO', 'AZUCAR', 'SUITE', 'SUPER', 'SURGE',
        'SURVEY', 'NADAR', 'TACKLE', 'EQUIPO', 'TEMPO',
        'TENIS', 'DECIMO', 'TERCERO', 'LANZAR', 'AJUSTE',
        'TIEMPO', 'TITULO', 'TOQUE', 'TORNEO', 'TORRE',
        'TRAYECTO', 'COMERCIO', 'TRAIL', 'TREN', 'RASGO',
        'TRAMP', 'ARRASTRE', 'TRATAR', 'TENDENCIA', 'TRIAL',
        'TRIBU', 'TRUCO', 'INTENTADO', 'TRIPLE', 'TROFEO',
        'CAMION', 'VERDADERO', 'TRUMP', 'TRONCO', 'CESPED',
        'GIRO', 'ULTRA', 'UMP', 'BAJO', 'UNION',
        'UNIR', 'UNIDAD', 'SUPERIOR', 'ALTERADO', 'URBANO',
        'USO', 'USUAL', 'VALIDO', 'VALOR', 'VAULT',
        'VERSO', 'VIGOR', 'VINYL', 'VIRUS', 'VISITA',
        'VISTA', 'VITAL', 'VIVID', 'VOCAL', 'VOZ',
        'VOTANTE', 'CINTURA', 'DESECHO', 'RELOJ', 'AGUA',
        'OLA', 'USAR', 'CUÑA', 'RARO', 'RUEDA',
        'DONDE', 'CUAL', 'MIENTRAS', 'BLANCO', 'ENTERO',
        'ANCHO', 'GANAR', 'VIENTO', 'ALAS', 'PARPADear',
        'GANAS', 'FIRME', 'SABIO', 'DESEAR', 'DENTRO',
        'MAGO', 'DESPIERTO', 'LOBO', 'MUJER', 'MADERA',
        'TRABAJAR', 'MUNDO', 'PREOCUPARSE', 'PEOR', 'PEOR',
        'VALER', 'PODRIA', 'HERIDA', 'ENVOLVER', 'MUÑECA',
        'ESCRIBIR', 'EQUIVOCADO', 'LUCHA', 'YATE', 'YAR',
        'HILO', 'AÑO', 'GRITAR', 'CEDER', 'YUGO',
        'JOVEN', 'TUYO', 'JOVEN', 'ZONA',
      ],
    },
  ),
  WordleCategory(
    id: 'music',
    name: {'en': 'Music', 'es': 'Música'},
    description: {'en': 'Bands, genres & instruments', 'es': 'Bandas, géneros e instrumentos'},
    icon: Icons.music_note,
    color: Color(0xFFE84393),
    words: {
      'en': [
        'ACOUSTIC', 'AFRO', 'ALTO', 'AMPS', 'ANGEL',
        'BACH', 'BANJO', 'BARITONE', 'BASS', 'BEAT',
        'BEETHOVEN', 'BLUES', 'BONGO', 'BOSSA', 'BRASS',
        'BREATH', 'BRITT', 'BRONX', 'BUSH', 'CELLO',
        'CHEST', 'CHINA', 'CHOIR', 'CHORD', 'CHORUS',
        'CLEF', 'CLUB', 'CRAZY', 'CREAM', 'CREED',
        'CRESCENDO', 'CRU', 'CUBAN', 'CYMBAL', 'DALI',
        'DANCE', 'DIAMOND', 'DISCO', 'DIVA', 'DJ',
        'DRAGON', 'DRAMA', 'DRUM', 'DUBSTEP', 'EARLY',
        'ELECTRO', 'ENYA', 'FADO', 'FALSE', 'FENDER',
        'FEST', 'FIDDLE', 'FLAC', 'FLUTE', 'FOLK',
        'FOXX', 'FREDDIE', 'FROG', 'FUNK', 'FURY',
        'GARAGE', 'GIBSON', 'GIG', 'GLAM', 'GONG',
        'GOSPEL', 'GRIME', 'GRUNGE', 'GUITAR', 'GYM',
        'HARMONY', 'HARP', 'HAWAII', 'HEAD', 'HEART',
        'HIPHOP', 'HOUSE', 'HOWL', 'HULA', 'HYMN',
        'INDIE', 'ION', 'JACK', 'JAZZ', 'JIVE',
        'JOEL', 'JOPLIN', 'JOS', 'JUAN', 'KARMA',
        'KEY', 'KEYBOARD', 'KISS', 'KOREAN', 'LAMB',
        'LARGE', 'LENO', 'LIGHT', 'LIL', 'LYRIC',
        'MACK', 'MADONNA', 'MAHAL', 'MAJOR', 'MALIBU',
        'MALLET', 'MANDO', 'MARACA', 'MARLEY', 'MAXWELL',
        'MELODIC', 'MELON', 'MICHAEL', 'MIDI', 'MILES',
        'MILK', 'MIXER', 'MODE', 'MOTOWN', 'MOVIE',
        'MUSIC', 'NIRVANA', 'NOTE', 'OASIS', 'OPERA',
        'ORGAN', 'OSCAR', 'OUTKAST', 'PACHELBEL', 'PANDORA',
        'PARK', 'PARTY', 'PAST', 'PEARL', 'PEDAL',
        'PHARRELL', 'PIANO', 'PICCOLO', 'PIZZA', 'PLUG',
        'POLKA', 'POP', 'PRINCE', 'PRODIGY', 'PSY',
        'RAVE', 'RAY', 'RECORD', 'REGGAE', 'REMIX',
        'RHAPSODY', 'RIFF', 'RIOT', 'RITMO', 'ROCK',
        'ROLL', 'ROSA', 'ROSE', 'ROW', 'RUMBLE',
        'RUN', 'RYAN', 'SALSA', 'SAX', 'SAXOPHONE',
        'SCAT', 'SCOOTER', 'SCORPIONS', 'SEGUE', 'SESH',
        'SHAKIRA', 'SHOW', 'SHREK', 'SING', 'SKA',
        'SLASH', 'SLAYER', 'SLOW', 'SMALL', 'SMITH',
        'SOLO', 'SONG', 'SOUL', 'SOUSA', 'SOUND',
        'SOUNDGARDEN', 'SOUP', 'SPANISH', 'SPEED', 'SPRING',
        'SQUEEZE', 'STAIN', 'STAMP', 'STAND', 'STARS',
        'START', 'STEEL', 'STEVE', 'STING', 'STOMP',
        'STORY', 'STRING', 'STUDIO', 'STYLES', 'SUBSONIC',
        'SUGABABES', 'SUMMER', 'SUN', 'SUPER', 'SURF',
        'SYMPHONY', 'TAB', 'TALENT', 'TANGO', 'TAPE',
        'TEMPO', 'TENOR', 'THEREMIN', 'THIRD', 'THROW',
        'TIE', 'TIMBA', 'TITAN', 'TOM', 'TONY',
        'TOOL', 'TRANCE', 'TRASH', 'TRAV', 'TRIBUTE',
        'TRIPLE', 'TROMBONE', 'TUBA', 'TUNE', 'TUPAC',
        'TURN', 'TWENTY', 'TWIST', 'ULTRA', 'UNDER',
        'UNION', 'VAN', 'VANILLA', 'VERSE', 'VIOLIN',
        'VIVALDI', 'VOCAL', 'VOICE', 'VOLUME', 'WAGNER',
        'WAIL', 'WAVE', 'WEDDING', 'WHITE', 'WHO',
        'WILSON', 'WIND', 'WIRE', 'WOOD', 'WOODSTOCK',
        'WORLD', 'YELLOW', 'YETI', 'ZAPPA', 'ZEIT',
      ],
      'es': [
        'ACUSTICO', 'AFRO', 'ALTO', 'AMP', 'ANGEL',
        'BACH', 'BANJO', 'BARITONE', 'BAJO', 'BEAT',
        'BEETHOVEN', 'BLUES', 'BONGO', 'BOSSA', 'BRASS',
        'ALIENTO', 'BRITT', 'BRONX', 'BUSH', 'CELLO',
        'PECHO', 'CHINA', 'CORO', 'ACORDE', 'CORO',
        'CLAVE', 'CLUB', 'CREAM', 'CREED', 'CRESCENDO',
        'CRU', 'CUBANO', 'TIMBAL', 'DALI', 'BAILE',
        'DIAMANTE', 'DISCO', 'DIVA', 'DJ', 'DRAGON',
        'DRAMA', 'TAMBOR', 'DUBSTEP', 'EARLY', 'ELECTRO',
        'ENYA', 'FADO', 'FALSO', 'FENDER', 'FEST',
        'VIOLIN', 'FLAC', 'FLAUTA', 'FOLK', 'FOXX',
        'FREDDIE', 'RANA', 'FUNK', 'FURIA', 'GARAGE',
        'GIBSON', 'GIG', 'GLAM', 'GONG', 'GOSPEL',
        'GRIME', 'GRUNGE', 'GUITARRA', 'GYM', 'HARMONY',
        'ARP', 'HAWAII', 'CABEZA', 'CORAZON', 'HIPHOP',
        'CASA', 'AULLIDO', 'HULA', 'HIMNO', 'INDIE',
        'ION', 'JACK', 'JAZZ', 'JIVE', 'JOEL',
        'JOPLIN', 'JOS', 'JUAN', 'KARMA', 'CLAVE',
        'TECLADO', 'BESO', 'COREANO', 'CORDERO', 'LARGO',
        'LENO', 'LUZ', 'LIL', 'LIRICA', 'MACK',
        'MADONNA', 'MAHAL', 'MAYOR', 'MALIBU', 'MALLET',
        'MANDO', 'MARACA', 'MARLEY', 'MAXWELL', 'MELODICO',
        'MELON', 'MICHAEL', 'MIDI', 'MILES', 'LECHE',
        'MEZCLADOR', 'MODO', 'MOTOWN', 'PELICULA', 'MUSICA',
        'NIRVANA', 'NOTA', 'OASIS', 'OPERA', 'ORGANO',
        'OSCAR', 'OUTKAST', 'PACHELBEL', 'PANDORA', 'PARQUE',
        'FIESTA', 'PASADO', 'PERLA', 'PEDAL', 'PHARRELL',
        'PIANO', 'PICCOLO', 'PIZZA', 'ENCHUFE', 'POLKA',
        'POP', 'PRINCE', 'PRODIGY', 'PSY', 'RAVE',
        'RAY', 'RECORD', 'REGGAE', 'REMIX', 'RHAPSODY',
        'RIFF', 'RIOT', 'RITMO', 'ROCK', 'ROLL',
        'ROSA', 'ROSE', 'FILA', 'RUMBLE', 'CORRER',
        'RYAN', 'SALSA', 'SAX', 'SAXOFON', 'SCAT',
        'SCOOTER', 'SCORPIONS', 'SEGUE', 'SESH', 'SHAKIRA',
        'SHOW', 'SHREK', 'CANTAR', 'SKA', 'SLASH',
        'SLAYER', 'LENTO', 'PEQUENO', 'SMITH', 'SOLO',
        'CANCION', 'ALMA', 'SOUSA', 'SONIDO', 'SOUNDGARDEN',
        'SOPA', 'ESPANOL', 'VELOCIDAD', 'PRIMAVERA', 'SQUEEZE',
        'MANCHA', 'ESTAMPA', 'PARARSE', 'ESTRELLAS', 'INICIO',
        'ACERO', 'STEVE', 'STING', 'STOMP', 'HISTORIA',
        'CUERDA', 'ESTUDIO', 'ESTILOS', 'SUBSONIC', 'SUGABABES',
        'VERANO', 'SOL', 'SUPER', 'SURF', 'SINFONIA',
        'TAB', 'TALENTO', 'TANGO', 'CINTA', 'TEMPO',
        'TENOR', 'THEREMIN', 'TERCERO', 'LANZAR', 'CORBATA',
        'TIMBA', 'TITAN', 'TOM', 'TONY', 'HERRAMIENTA',
        'TRANCE', 'BASURA', 'TRAV', 'TRIBUTE', 'TRIPLE',
        'TROMBONE', 'TUBA', 'TUNE', 'TUPAC', 'VOLTA',
        'TWENTY', 'TWIST', 'ULTRA', 'BAJO', 'UNION',
        'VAN', 'VANILLA', 'VERSO', 'VIOLIN', 'VIVALDI',
        'VOCAL', 'VOZ', 'VOLUMEN', 'WAGNER', 'WAHL',
        'OLA', 'BODA', 'BLANCO', 'QUIEN', 'WILSON',
        'VIENTO', 'ALAMBRE', 'MADERA', 'WOODSTOCK', 'MUNDO',
        'AMARILLO', 'YETI', 'ZAPPA', 'ZEIT',
      ],
    },
  ),
  WordleCategory(
    id: 'tech',
    name: {'en': 'Technology', 'es': 'Tecnología'},
    description: {'en': 'Gadgets, companies & more', 'es': 'Gadgets, empresas y más'},
    icon: Icons.computer,
    color: Color(0xFF00CEC9),
    words: {
      'en': [
        'ABACUS', 'AGILE', 'ALERT', 'ALIAS', 'ALPHA',
        'AMAZON', 'ANDROID', 'ANGULAR', 'APPLE', 'APPS',
        'AUDIO', 'BAND', 'BASIC', 'BATCH', 'BINARY',
        'BIT', 'BITCOIN', 'BLOCK', 'BLOG', 'BLUETOOTH',
        'BOARD', 'BOOT', 'BRAIN', 'BREAD', 'BROWSER',
        'BYTE', 'CACHE', 'CABLE', 'CAMERA', 'CANVA',
        'CARRY', 'CASE', 'CISCO', 'CLICK', 'CLOUD',
        'CODE', 'COLOR', 'COMET', 'COMPANY', 'CORE',
        'CPU', 'CRYPTO', 'CYBER', 'DATA', 'DEBUG',
        'DELL', 'DELTA', 'DEPLOY', 'DIGIT', 'DISK',
        'DOMAIN', 'DOWNLOAD', 'DRONE', 'DRUID', 'EARTH',
        'EMAIL', 'ETHER', 'EVENT', 'EXCEL', 'FACT',
        'FAIR', 'FAX', 'FIBER', 'FILE', 'FIREFOX',
        'FLICK', 'FLUX', 'FORK', 'FRAME', 'FRESH',
        'FRONT', 'GAMES', 'GATE', 'GITHUB', 'GLYPH',
        'GOOGLE', 'GRIDS', 'GROUP', 'GROW', 'GUARD',
        'GUID', 'HACK', 'HARRY', 'HARVARD', 'HELLO',
        'HINT', 'HIT', 'HOLD', 'HOST', 'HP',
        'HTTP', 'HUB', 'HYBRID', 'IMAGE', 'INDEX',
        'INK', 'INPUT', 'INSTAGRAM', 'INTEL', 'INTERNET',
        'IOT', 'ITER', 'JAVA', 'JAVASCRIPT', 'JPEG',
        'JSON', 'KERNEL', 'KEY', 'KEYBOARD', 'KILL',
        'LAND', 'LAPTOP', 'LAUNCH', 'LINK', 'LINUX',
        'LOGO', 'LONELY', 'LOOP', 'MAC', 'MACOS',
        'MAIL', 'MAIN', 'MAP', 'MARK', 'MEDIA',
        'META', 'MICROSOFT', 'MODEM', 'MONITOR', 'MOUSE',
        'MUSIC', 'NAN', 'NET', 'NETWORK', 'NODE',
        'NOTE', 'NPM', 'NULL', 'OBJECT', 'OFFICE',
        'ONLINE', 'OPEN', 'OPERA', 'OS', 'OUTLOOK',
        'PIXEL', 'PLANE', 'PLAN', 'POINT', 'PONG',
        'POWER', 'PRINT', 'PRINTER', 'PROCESS', 'PROGRAM',
        'PUSH', 'QUERY', 'QUEUE', 'QUICK', 'RADIO',
        'RAID', 'READ', 'REAL', 'REBOOT', 'RENDER',
        'REST', 'RICH', 'RING', 'ROBOT', 'ROOT',
        'ROSE', 'ROUTER', 'RUN', 'SAMSUNG', 'SCAN',
        'SCENE', 'SCOPE', 'SCREEN', 'SCROLL', 'SEARCH',
        'SECURE', 'SERVER', 'SHARE', 'SHIFT', 'SHIRT',
        'SHOP', 'SHOT', 'SITE', 'SLACK', 'SMART',
        'SOLID', 'SONY', 'SOURCE', 'SPACE', 'SPAM',
        'SPHERE', 'SPOT', 'SPREAD', 'SQL', 'STACK',
        'STAR', 'START', 'STATE', 'STEAM', 'STICK',
        'STOCK', 'STORE', 'STORY', 'STUDIO', 'STYLE',
        'SUN', 'SUPER', 'SURF', 'SWIFT', 'TABLE',
        'TABLET', 'TECH', 'TELEGRAM', 'TERMINAL', 'THEME',
        'THING', 'THINK', 'TOKEN', 'TRACK', 'TRANSFER',
        'TREE', 'TRUMP', 'TWITTER', 'TYPE', 'ULTRA',
        'UNIX', 'UPDATE', 'USB', 'USER', 'VALID',
        'VALUE', 'VIDEO', 'VIRUS', 'VISUAL', 'VOLUME',
        'VPN', 'WALK', 'WALL', 'WARE', 'WEB',
        'WEBSITE', 'WIDGET', 'WIFI', 'WIKI', 'WINDOWS',
        'WIRE', 'WORD', 'WORDPRESS', 'WORK', 'WRITE',
        'XBOX', 'YAHOO', 'YOUTUBE', 'ZOOM',
      ],
      'es': [
        'ABACO', 'AGIL', 'ALERTA', 'ALIAS', 'ALFA',
        'AMAZON', 'ANDROID', 'ANGULAR', 'APPLE', 'APPS',
        'AUDIO', 'BANDA', 'BASICO', 'BATCH', 'BINARIO',
        'BIT', 'BITCOIN', 'BLOQUE', 'BLOG', 'BLUETOOTH',
        'TABLERO', 'BOOT', 'CEREBRO', 'PAN', 'NAVEGADOR',
        'BYTE', 'CACHE', 'CABLE', 'CAMARA', 'CANVA',
        'LLEVAR', 'CASE', 'CISCO', 'CLICK', 'NUBE',
        'CODIGO', 'COLOR', 'COMETA', 'COMPANIA', 'NUCLEO',
        'CPU', 'CRYPTO', 'CYBER', 'DATOS', 'DEBUG',
        'DELL', 'DELTA', 'DESPLIEGUE', 'DIGITO', 'DISCO',
        'DOMINIO', 'DESCARGA', 'DRON', 'DRUID', 'TIERRA',
        'EMAIL', 'ETHER', 'EVENTO', 'EXCEL', 'HECHO',
        'JUSTO', 'FAX', 'FIBER', 'ARCHIVO', 'FIREFOX',
        'FLICK', 'FLUX', 'BIFURCAR', 'MARCO', 'FRESCO',
        'FRENTE', 'JUEGOS', 'PUERTA', 'GITHUB', 'GLYPH',
        'GOOGLE', 'GRIDS', 'GRUPO', 'CRECER', 'GUARDAR',
        'GUID', 'HACK', 'HARRY', 'HARVARD', 'HOLA',
        'PISTA', 'GOLPE', 'MANTENER', 'HOST', 'HP',
        'HTTP', 'HUB', 'HIBRIDO', 'IMAGEN', 'INDICE',
        'TINTA', 'ENTRADA', 'INSTAGRAM', 'INTEL', 'INTERNET',
        'IOT', 'ITER', 'JAVA', 'JAVASCRIPT', 'JPEG',
        'JSON', 'KERNEL', 'CLAVE', 'TECLADO', 'MATAR',
        'TIERRA', 'PORTATIL', 'LANZAR', 'ENLACE', 'LINUX',
        'LOGO', 'LONELY', 'BUCLE', 'MAC', 'MACOS',
        'CORREO', 'PRINCIPAL', 'MAPA', 'MARCA', 'MEDIA',
        'META', 'MICROSOFT', 'MODEM', 'MONITOR', 'RATON',
        'MUSICA', 'NAN', 'RED', 'RED', 'NODO',
        'NOTA', 'NPM', 'NULL', 'OBJETO', 'OFICINA',
        'EN_LINEA', 'ABIERTO', 'OPERA', 'SO', 'OUTLOOK',
        'PIXEL', 'AVION', 'PLAN', 'PUNTO', 'PONG',
        'PODER', 'IMPRIMIR', 'IMPRESORA', 'PROCES', 'PROGRAMA',
        'EMPUJAR', 'CONSULTA', 'COLA', 'RAPIDO', 'RADIO',
        'RAID', 'LEER', 'REAL', 'REINICIAR', 'RENDERIZAR',
        'REST', 'RICO', 'ANILLO', 'ROBOT', 'RAIZ',
        'ROSA', 'ENRUTADOR', 'CORRER', 'SAMSUNG', 'ESCANEAR',
        'ESCENA', 'AMBITO', 'PANTALLA', 'DESPLAZAR', 'BUSCAR',
        'SEGURO', 'SERVIDOR', 'COMPARTIR', 'CAMBIAR', 'CAMISA',
        'TIENDA', 'DISPARO', 'SITIO', 'SLACK', 'INTELIGENTE',
        'SOLIDO', 'SONY', 'FUENTE', 'ESPACIO', 'SPAM',
        'ESFERA', 'SPOT', 'EXTENDER', 'SQL', 'PILA',
        'ESTRELLA', 'INICIO', 'ESTADO', 'VAPOR', 'BASTON',
        'ACCIONES', 'TIENDA', 'HISTORIA', 'ESTUDIO', 'ESTILO',
        'SOL', 'SUPER', 'SURF', 'SWIFT', 'MESA',
        'TABLETA', 'TECH', 'TELEGRAM', 'TERMINAL', 'TEMA',
        'COSA', 'PENSAR', 'TOKEN', 'RASTREAR', 'TRANSFERIR',
        'ARBOL', 'TRUMP', 'TWITTER', 'TIPO', 'ULTRA',
        'UNIX', 'ACTUALIZAR', 'USB', 'USUARIO', 'VALIDO',
        'VALOR', 'VIDEO', 'VIRUS', 'VISUAL', 'VOLUMEN',
        'VPN', 'CAMINAR', 'PARED', 'WARE', 'WEB',
        'SITIOWEB', 'WIDGET', 'WIFI', 'WIKI', 'WINDOWS',
        'ALAMBRE', 'PALABRA', 'WORDPRESS', 'TRABAJAR', 'ESCRIBIR',
        'XBOX', 'YAHOO', 'YOUTUBE', 'ZOOM',
      ],
    },
  ),
];
